apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
        type: app
    spec:
      containers:
      - name: nestjs-app
        image: "859868612949.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:latest"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 0.25Gi
          requests:
            cpu: 100m
            memory: 0.25Gi
        ports:
        - name: http
          containerPort: 3000

