---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
  labels:
    app: nestjs-app
spec:
  type: LoadBalancer
  selector:
    app: nestjs-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  
